# Generated by Django 5.0.1 on 2024-03-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteitem',
            name='quantity',
        ),
    ]
