# Generated by Django 5.0.1 on 2024-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='booked', max_length=200),
        ),
    ]
