# Generated by Django 5.0.1 on 2024-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_payment_remove_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteitem',
            name='is_order_placed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
